### PR TITLE
input attributes: 'require', 'multiple'

### PR DESCRIPTION
**Pull request by itsazzad**
input attributes: require and multiple for type file

### CODE REVIEW

**Comment by MrAntix** [comment]
@itsazzad, shouldn't that be "required"?

http://www.w3.org/wiki/HTML5_form_additions

If we added these, should we add the rest?
Also, changing the defaults is a breaking change, should be a version increment and needs documenting

**Comment by MrAntix** [comment]
Btw, thanks for taking the time to submit

**Comment by itsazzad** [comment]
@MrAntix  I am so sorry. I misspelled and just corrected

**Comment by MrAntix** [comment]
Sorry I can't accept this as its a breaking change which would disrupt existing users and is only a partial support for the standards

You can add these optionally in your own config anyway

**Pull request closed without merging**
